### ISSUE TITLE
INSTALL.md step 4 not working

### ISSUE THREAD

**Issue by theod** [lii-enac/smala#2]
Hi,
I'm starting to use Smala for the first time.

In [INSTALL.md](INSTALL.md) the first command of step 4. doesn't work.

`make -j pan_and_zoom_test
make: *** No rule to make target `pan_and_zoom_test'.  Stop.`

There is a cookbook/gui/direct_manipulation/drag_pan_zoom folder but I can't found the way to make it to work from the root smala folder.

Best regards,
TO

**Comment by mpoirier-enac** [comment]
thanks for your reply.

it has been fixed

Mathieu
